### ISSUE TITLE
重複して必要ない行

### ISSUE THREAD

**Issue by c0a2107793** [nagahamakouki/ProjExD#5]
https://github.com/nagahamakouki/ProjExD/blob/91f5fd3c9f558a7c862ce2a8fb923309ed3f7d02/ex02/calc.py#L28

このようなプログラムが良く見られるが、if,elseから出せば、１回で済むのではないかと感じた。

**Comment by nagahamakouki** [comment]
すこしスッキリしました。
コメントありがとうございます。
